---
- name: Symlink VSCode settings
  file:
    src: '{{ role_path }}/files/VSCode/{{ item }}'
    dest: '{{ home_dir }}/Library/Application Support/Code/User/{{ item }}'
    state: link
    force: yes
  with_items:
    - keybindings.json
    - settings.json
    - snippets
  tags:
    - vscode

- name: Register VSCode extensions list
  shell: 'cat {{ role_path }}/files/VSCode/extensions_list'
  register: cat_vscode_extensions
  tags:
    - vscode

- name: Install VSCode extensions
  shell: 'code --install-extension {{ item }}'
  with_items: '{{ cat_vscode_extensions.stdout_lines }}'
  tags:
    - vscode
